### PR TITLE
Make some bad changes so that format can work

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by weiji14** [comment]
Will need to update this `test-slash` branch with the new changes in `seisman:master` at 189921c99fae93bfd114bd8d3e47579b9d922352 to test the GMT App token out.

**Comment by seisman** [comment]
I've merged the master branch and made some bad changes again in commit 4d963dac47d24e80e05e502a001fb3565500a896.

**Comment by seisman** [comment]
This is the job status for your `/format` command. It seems you don't have written permission to my repository?

```
Command 'format' is not configured for the user's permission level 'none'.
```

**Comment by weiji14** [comment]
> This is the job status for your `/format` command. It seems you don't have written permission to my repository?
> 
> ```
> Command 'format' is not configured for the user's permission level 'none'.
> ```

Yeah, will this be a problem for contributors to GenericMappingTools/pygmt? Looking at https://github.com/peter-evans/slash-command-dispatch#permission, it seems that we could set the permission level to None perhaps?

**Comment by seisman** [comment]
> Yeah, will this be a problem for contributors to GenericMappingTools/pygmt? 

Perhaps not. When a contributor opens a PR, he/she has the written permission to his own repo's branch. If he/she "allows edits from maintainers", then we also have written permission to that branch. 

> Looking at https://github.com/peter-evans/slash-command-dispatch#permission, it seems that we could set the permission level to None perhaps?

We could, but perhaps it means anyone (even someone we don't know) can trigger the `/format` command? It's unsafe to me.

**Comment by weiji14** [comment]
> > Yeah, will this be a problem for contributors to GenericMappingTools/pygmt?
> 
> Perhaps not. When a contributor opens a PR, he/she has the written permission to his own repo's branch. If he/she "allows edits from maintainers", then we also have written permission to that branch.
> 
> > Looking at https://github.com/peter-evans/slash-command-dispatch#permission, it seems that we could set the permission level to None perhaps?
> 
> We could, but perhaps it means anyone (even someone we don't know) can trigger the `/format` command? It's unsafe to me.

**Comment by weiji14** [comment]
Looking at https://github.com/peter-evans/slash-command-dispatch-processor/blob/master/.github/workflows/black-command.yml, it doesn't seem like 'permissions' was set though. Maybe I'm just overthinking it and we don't have to care about this.

Could you run /format on your end @seisman and test it out?

**Comment by seisman** [comment]
> Looking at https://github.com/peter-evans/slash-command-dispatch-processor/blob/master/.github/workflows/black-command.yml, it doesn't seem like 'permissions' was set though. Maybe I'm just overthinking it and we don't have to care about this.

The default permission is `write`. https://github.com/peter-evans/slash-command-dispatch#action-inputs

**Comment by weiji14** [comment]
Yep, it needs the `APP_ID` secret which is only on GenericMappingTools/pygmt. Let's go back there and finish up that PR, I think it should work.

**Pull request closed without merging**
